version : "3"


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /docker-entrypoint.sh
    container_name: support_app
    volumes:
      - ./:/docker-compose.yml
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    depends_on:
      - db
      - cache

  db:
    image: postgres:latest
    container_name: support_db
    env_file:
      - .env.example
    environment:
      - LANG:'ja_JP.UTF-8'
      - LANGUAGE:'ja_JP.UTF-8'
      - LC_ALL:'ja_JP.UTF-8'

  adminer:
    image: adminer:latest
    container_name: support_app_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

  cache:
    image: redis:latest
    container_name: support_redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: support_celery
    volumes:
      - ./support:/support
    env_file:
      - .env.example
    depends_on:
      - db
      - cache
    command: celery -A support worker -l INFO
